services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contact_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__myQueryString=Server=db;Database=ContactDB;User=sa;Password=Your_Strong_Password123!;TrustServerCertificate=True;MultipleActiveResultSets=true

  db:
    image: mcr.microsoft.com/mssql/server:2022-CU16-ubuntu-22.04
    container_name: contact_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_Strong_Password123!
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data:
